server:
  port: 1118
spring:
  application:
    name: hystrix
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
feign:
  hystrix:
    enabled: true

management:
 endpoints:
   web:
     exposure:
       include: 'hystrix.stream'
hystrix:
  dashboard:
    proxy-stream-allow-list: "localhost"
